Added player and obstacle images
utmgdsc/dino-game pull request #15
Opened 2023-12-27 23:41 UTC by renee-k

Made one dino image for the player art. Made three obstacle images that are randomly selected to be displayed in gameplay.

2023-12-27 23:46 UTC, ggggg requested changes
Thank you for contributing, this is a great PR!
Just a couple of small changes before we merge.

2023-12-27 23:46 UTC, ggggg commented on Obstacle.py
> +        # self.height = random.randint(MIN_HEIGHT, MAX_HEIGHT)
```suggestion
```

No need for this code

2023-12-27 23:46 UTC, ggggg commented on Obstacle.py
> +        # pg.draw.rect(surface, self.color, self.rect)
```suggestion
```

2023-12-27 23:46 UTC, ggggg commented on Player.py
> +        # pg.draw.rect(surface, PLAYER_COLOR, self.rect)
```suggestion
```

2023-12-27 23:46 UTC, ggggg commented on constants.py
> +GRASS_HEIGHT = 90
Can we make these a bit smaller? the game is a bit hard to play at the moment

2023-12-28 05:49 UTC, renee-k commented
Thanks for the feedback I believe the images should be small enough now!

2023-12-30 06:53 UTC, ggggg commented
Can you make them even smaller? The game is not really playable right now with those sizes

2023-12-30 09:34 UTC, ggggg approved these changes

2023-12-30 09:34 UTC, merged